---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - powershell
      - naisdevice
      - docker
      - firefox
      - google-chrome
      - google-drive
      - iterm2
      - slack
    brew_packages:
      - ansible
      - azure-cli
      - bicep
      - ca-certificates
      - git
      - wget
      - zsh
      - python@3.10
      - openssl@3
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: copy .zshrc file
      copy:
        src: files/.zshrc
        dest: /Users/steinarvollebaek/.zshrc
        owner: steinarvollebaek
        group: staff

    - name: copy .gitconfig file
      copy:
        src: files/.gitconfig
        dest: /Users/steinarvollebaek/.gitconfig
        owner: steinarvollebaek
        group: staff

    - name: copy alwaysAdmin file
      copy:
        src: files/alwaysAdmin.sh
        dest: /Users/steinarvollebaek/bin/alwaysAdmin.sh
        owner: steinarvollebaek
        group: staff

    - name: add alwaysAdmin cron job
      cron:
        name: always be admin
        user: steinarvollebaek
        minute: "*/5"
        job: cd ~/bin && ./alwaysAdmin.sh

    - name: copy update-all file
      copy:
        src: files/update-all.sh
        dest: /Users/steinarvollebaek/update-all.sh
        owner: steinarvollebaek
        group: staff

    - name: add update-all cron job
      cron:
        name: update all
        user: steinarvollebaek
        minute: "*/30"
        job: cd ~/bin && ./update-all.sh

    - name: add ansible user
      become: true
      user:
        name: ansibleDaemon
        system: yes

    - name: set up sudo for ansible user
      become: true
      copy:
        src: files/sudoer_ansibleDaemon
        dest: /etc/sudoers.d/ansibleDaemon
        owner: root
        group: wheel
        mode: 0440

    - name: add ansible-pull cron job
      become: true
      cron:
        name: ansible auto-provision
        user: ansibleDaemon
        minute: "*/5"
        job: ansible-pull -o -U https://github.com/errordodge/ansible_desktop.git
